Fix javadoc 'error: cannot find symbol'
Javadoc could not find classes from Android support libraries,
causing it to throw errors.

To fix this, classes from external libraries are now explicitly added
to the javadoc classpath via a Gradle afterEvaluate { } block.